// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kafka_events.proto

package proto

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId      *UUID                  `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IdempotencyKey *UUID                  `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	InstrumentId   *UUID                  `protobuf:"bytes,4,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	OrderBy        OrderBy                `protobuf:"varint,5,opt,name=order_by,json=orderBy,proto3,enum=order.v1.OrderBy" json:"order_by,omitempty"`
	Quantity       *decimal.Decimal       `protobuf:"bytes,6,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	Amount         *money.Money           `protobuf:"bytes,7,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	Side           OrderSide              `protobuf:"varint,8,opt,name=side,proto3,enum=order.v1.OrderSide" json:"side,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderEvent) Reset() {
	*x = CreateOrderEvent{}
	mi := &file_kafka_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderEvent) ProtoMessage() {}

func (x *CreateOrderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderEvent.ProtoReflect.Descriptor instead.
func (*CreateOrderEvent) Descriptor() ([]byte, []int) {
	return file_kafka_events_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderEvent) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateOrderEvent) GetAccountId() *UUID {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *CreateOrderEvent) GetIdempotencyKey() *UUID {
	if x != nil {
		return x.IdempotencyKey
	}
	return nil
}

func (x *CreateOrderEvent) GetInstrumentId() *UUID {
	if x != nil {
		return x.InstrumentId
	}
	return nil
}

func (x *CreateOrderEvent) GetOrderBy() OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return OrderBy_ORDER_BY_UNSPECIFIED
}

func (x *CreateOrderEvent) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *CreateOrderEvent) GetAmount() *money.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CreateOrderEvent) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

type OrderResultEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *UUID                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Side          OrderSide              `protobuf:"varint,2,opt,name=side,proto3,enum=order.v1.OrderSide" json:"side,omitempty"`
	OrderBy       OrderBy                `protobuf:"varint,3,opt,name=order_by,json=orderBy,proto3,enum=order.v1.OrderBy" json:"order_by,omitempty"`
	Status        OrderStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	Price         *money.Money           `protobuf:"bytes,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Amount        *money.Money           `protobuf:"bytes,6,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,7,opt,name=quantity,proto3,oneof" json:"quantity,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResultEvent) Reset() {
	*x = OrderResultEvent{}
	mi := &file_kafka_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResultEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResultEvent) ProtoMessage() {}

func (x *OrderResultEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kafka_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResultEvent.ProtoReflect.Descriptor instead.
func (*OrderResultEvent) Descriptor() ([]byte, []int) {
	return file_kafka_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderResultEvent) GetId() *UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *OrderResultEvent) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *OrderResultEvent) GetOrderBy() OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return OrderBy_ORDER_BY_UNSPECIFIED
}

func (x *OrderResultEvent) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderResultEvent) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderResultEvent) GetAmount() *money.Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *OrderResultEvent) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *OrderResultEvent) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

var File_kafka_events_proto protoreflect.FileDescriptor

const file_kafka_events_proto_rawDesc = "" +
	"\n" +
	"\x12kafka_events.proto\x12\border.v1\x1a\vtypes.proto\x1a\x19google/type/decimal.proto\x1a\x17google/type/money.proto\x1a\vorder.proto\"\xa6\x03\n" +
	"\x10CreateOrderEvent\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\v2\x0e.order.v1.UUIDR\x02id\x12-\n" +
	"\n" +
	"account_id\x18\x02 \x01(\v2\x0e.order.v1.UUIDR\taccountId\x127\n" +
	"\x0fidempotency_key\x18\x03 \x01(\v2\x0e.order.v1.UUIDR\x0eidempotencyKey\x123\n" +
	"\rinstrument_id\x18\x04 \x01(\v2\x0e.order.v1.UUIDR\finstrumentId\x12,\n" +
	"\border_by\x18\x05 \x01(\x0e2\x11.order.v1.OrderByR\aorderBy\x125\n" +
	"\bquantity\x18\x06 \x01(\v2\x14.google.type.DecimalH\x00R\bquantity\x88\x01\x01\x12/\n" +
	"\x06amount\x18\a \x01(\v2\x12.google.type.MoneyH\x01R\x06amount\x88\x01\x01\x12'\n" +
	"\x04side\x18\b \x01(\x0e2\x13.order.v1.OrderSideR\x04sideB\v\n" +
	"\t_quantityB\t\n" +
	"\a_amount\"\xad\x03\n" +
	"\x10OrderResultEvent\x12\x1e\n" +
	"\x02id\x18\x01 \x01(\v2\x0e.order.v1.UUIDR\x02id\x12'\n" +
	"\x04side\x18\x02 \x01(\x0e2\x13.order.v1.OrderSideR\x04side\x12,\n" +
	"\border_by\x18\x03 \x01(\x0e2\x11.order.v1.OrderByR\aorderBy\x12-\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.order.v1.OrderStatusR\x06status\x12-\n" +
	"\x05price\x18\x05 \x01(\v2\x12.google.type.MoneyH\x00R\x05price\x88\x01\x01\x12/\n" +
	"\x06amount\x18\x06 \x01(\v2\x12.google.type.MoneyH\x01R\x06amount\x88\x01\x01\x125\n" +
	"\bquantity\x18\a \x01(\v2\x14.google.type.DecimalH\x02R\bquantity\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\b \x01(\tH\x03R\ferrorMessage\x88\x01\x01B\b\n" +
	"\x06_priceB\t\n" +
	"\a_amountB\v\n" +
	"\t_quantityB\x10\n" +
	"\x0e_error_messageB3Z1github.com/cathudson/order-service/internal/protob\x06proto3"

var (
	file_kafka_events_proto_rawDescOnce sync.Once
	file_kafka_events_proto_rawDescData []byte
)

func file_kafka_events_proto_rawDescGZIP() []byte {
	file_kafka_events_proto_rawDescOnce.Do(func() {
		file_kafka_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kafka_events_proto_rawDesc), len(file_kafka_events_proto_rawDesc)))
	})
	return file_kafka_events_proto_rawDescData
}

var file_kafka_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kafka_events_proto_goTypes = []any{
	(*CreateOrderEvent)(nil), // 0: order.v1.CreateOrderEvent
	(*OrderResultEvent)(nil), // 1: order.v1.OrderResultEvent
	(*UUID)(nil),             // 2: order.v1.UUID
	(OrderBy)(0),             // 3: order.v1.OrderBy
	(*decimal.Decimal)(nil),  // 4: google.type.Decimal
	(*money.Money)(nil),      // 5: google.type.Money
	(OrderSide)(0),           // 6: order.v1.OrderSide
	(OrderStatus)(0),         // 7: order.v1.OrderStatus
}
var file_kafka_events_proto_depIdxs = []int32{
	2,  // 0: order.v1.CreateOrderEvent.id:type_name -> order.v1.UUID
	2,  // 1: order.v1.CreateOrderEvent.account_id:type_name -> order.v1.UUID
	2,  // 2: order.v1.CreateOrderEvent.idempotency_key:type_name -> order.v1.UUID
	2,  // 3: order.v1.CreateOrderEvent.instrument_id:type_name -> order.v1.UUID
	3,  // 4: order.v1.CreateOrderEvent.order_by:type_name -> order.v1.OrderBy
	4,  // 5: order.v1.CreateOrderEvent.quantity:type_name -> google.type.Decimal
	5,  // 6: order.v1.CreateOrderEvent.amount:type_name -> google.type.Money
	6,  // 7: order.v1.CreateOrderEvent.side:type_name -> order.v1.OrderSide
	2,  // 8: order.v1.OrderResultEvent.id:type_name -> order.v1.UUID
	6,  // 9: order.v1.OrderResultEvent.side:type_name -> order.v1.OrderSide
	3,  // 10: order.v1.OrderResultEvent.order_by:type_name -> order.v1.OrderBy
	7,  // 11: order.v1.OrderResultEvent.status:type_name -> order.v1.OrderStatus
	5,  // 12: order.v1.OrderResultEvent.price:type_name -> google.type.Money
	5,  // 13: order.v1.OrderResultEvent.amount:type_name -> google.type.Money
	4,  // 14: order.v1.OrderResultEvent.quantity:type_name -> google.type.Decimal
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_kafka_events_proto_init() }
func file_kafka_events_proto_init() {
	if File_kafka_events_proto != nil {
		return
	}
	file_types_proto_init()
	file_order_proto_init()
	file_kafka_events_proto_msgTypes[0].OneofWrappers = []any{}
	file_kafka_events_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kafka_events_proto_rawDesc), len(file_kafka_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kafka_events_proto_goTypes,
		DependencyIndexes: file_kafka_events_proto_depIdxs,
		MessageInfos:      file_kafka_events_proto_msgTypes,
	}.Build()
	File_kafka_events_proto = out.File
	file_kafka_events_proto_goTypes = nil
	file_kafka_events_proto_depIdxs = nil
}
